CREATE DATABASE user_task;
USE user_task;
CREATE TABLE USER
(
  id INT PRIMARY KEY IDENTITY(1,1),
  name VARCHAR(50)
);

CREATE TABLE TASK
(
  id_T INT PRIMARY KEY IDENTITY(1,1),
  desc VARCHAR(250),
  id INT NOT NULL,
  FOREIGN KEY (id) REFERENCES USER(id)
);